name: pluginenxtest
version: '1.0-SNAPSHOT'
main: com.ethamorim.pluginenxtest.EnxTestPlugin
api-version: '1.21'
commands:
  windcharge:
    description: "Change the functionality of the Wind Charge"
    usage: "/windcharge [set|give] <property> <value>"
    aliases: [wc]
